### ISSUE TITLE
Exception in browser on entering editor textarea

### ISSUE THREAD

**Issue by fynnfluegge** [fynnfluegge/rocketnotes#73]
Once entering the editor textarea a second time, which means
`edit` -> `place cursor in textarea` -> `cancel` -> `edit` -> `place cursor in textarea`
or 
`edit` -> `place cursor in textarea` -> `preview` -> `place cursor in textarea`
the following exception appears in the browser console:
```
Uncaught (in promise) Error: this.element.parentElement was null
    at i (general.js:102:1108422)
    at j.dao (general.js:299:99461)
    at j.destruct (general.js:299:86030)
    at general.js:299:104630
    at Set.forEach (<anonymous>)
    at L.setupEditorAfterValidation (general.js:299:104616)
    at L.visibilityCallback (general.js:299:104901)
    at L.initEditor (general.js:299:105031)
    at HTMLTextAreaElement.e (general.js:299:104077)
    at HTMLDocument.dispatch (general.js:102:390260)
Uncaught (in promise) Error: this.element.parentElement was null
    at i (general.js:102:1108422)
    at j.dao (general.js:299:99461)
    at j.destruct (general.js:299:86030)
    at general.js:299:85947
    at MutationObserver.observe.childList (general.js:102:1102740)
```

**Comment by fynnfluegge** [comment]
Fixed with https://github.com/fynnfluegge/rocketnotes/commit/8895d5dd87bf6ab133b4016afe218853b14a4005
